"""empty message

Revision ID: f7416199f979
Revises: 
Create Date: 2022-06-29 03:16:53.368859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7416199f979'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('server_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_users',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('server_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name='server_users_server_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='server_users_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'server_id', name='server_users_pkey')
    )
    op.drop_table('members')
    # ### end Alembic commands ###
